version: '3.8'
services:
  flask_api:
    build:
      context: ./python-api
    container_name: python_api
    ports:
      - "5000:5000"
    volumes:
      - "./python-api:/app"
    command: "python app.py"
    depends_on:
      - mysql_db
    networks:
      - app_networks
    env_file:
      - python-api/.env

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
    ports:
      - "3307:3306"
    networks:
      - app_networks
  
  node_api:
    build:
      context: ./node-api
    container_name: node_api
    ports:
      - "3000:3000"
    networks:
      - app_networks
    depends_on:
      - flask_api

networks:
  app_networks:
    driver: bridge